version: "3.8"

services:
  frontend:
    build:
      context: ./frontend/labs-ui
    container_name: vue_frontend
    ports:
      - "5173:5173"  # Exposes Vite's port 5173 to the host
    depends_on:
      - backend
    environment:
      - VUE_APP_API_URL=http://backend:8000
    networks:
      - app-network

  backend:
    build:
      context: ./backend/labs-api
    container_name: django_backend
    ports:
      - "8000:8000"  # Exposes the backend on port 8000
    volumes:
      - ./backend:/labs-api
    environment:
      - DEBUG=True
    command: python manage.py runserver 0.0.0.0:8000  # Starts Django server and listens on all IPs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge  # Use a bridge network for both services to communicate with each other

volumes:
  backend_data:
