# Generated by Django 5.2 on 2025-04-13 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labs',
            name='lab_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
